# Generated by Django 5.2.5 on 2025-08-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="premium",
            field=models.BooleanField(default=False, verbose_name="Premium"),
        ),
    ]
